# Generated by Django 5.1.4 on 2024-12-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minobrnauki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='actual_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
