# Generated by Django 5.1.4 on 2024-12-17 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minobrnauki', '0002_alter_userprofile_actual_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
