# Generated by Django 5.1.4 on 2024-12-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minobrnauki', '0003_application_application_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_number',
        ),
    ]
